### ISSUE TITLE
Request: hearted filter

### ISSUE THREAD

**Issue by sa2k** [patchstorage/patchstorage-issues#3]
It would be considerably useful if there was an option in each platform category to only show the hearted favorite patches for those who can use the info in each download page for each patch such as tutorial/video/info. Any chance of adding the feature soon? Users of patch storage can more easily redownloading and read about their favorite patches with the hearted patches shown only if the hearted only feature is selected.

**Comment by pranciskus** [comment]
You can see your liked patches here - https://patchstorage.com/settings/likes/. We will look into an option to implement a "liked" filter on the explore page.

**Comment by pranciskus** [comment]
Done! Could you please test it out, so I can close this?

**Comment by sa2k** [comment]
Looks like it’s working. Good feature to add, huh? Thanks for the addition!

Sam Abate

**Comment by pranciskus** [comment]
Great! If you have any other suggestions, let me know!
