### ISSUE TITLE
Ability to disable email notifications from platform requests

### ISSUE THREAD

**Issue by mark-orion** [patchstorage/patchstorage-issues#8]
I just voted for a new platform by leaving a comment. As a result I am getting loads of annoying emails  with often just '+1' as content. It is not obvious if there is a way to disable these email notifications or not.
Please implement a way to disable this type of email notification or if a method exists, then please make this more obvious.
If the mail settings in the top right corner of the web interface are meant to configure this, then the wording is very confusing:
The first checkbox implies to me that I allow others to send me direct messages.
The second looks like a toggle for email notifications of aforesaid messages, and the third looks like an option to get Patchstorage announcements mailed to me or not. Not a word about email notifications from comments threads.

The current implementation might even violate EU law as there is no link in the emails that offers an easy way to unsubscribe.

**Comment by pranciskus** [comment]
Thanks for your elaborate report. We will look into ways to revamp the notification settings asap.

**Comment by pranciskus** [comment]
Done! You can change comment notification settings here - https://patchstorage.com/settings/profile/#user_notifications_settings

**Comment by mark-orion** [comment]
> Done! You can change comment notification settings here - https://patchstorage.com/settings/profile/#user_notifications_settings

Thanks a lot for fixing this so quickly - Patchstorage rocks !
